# ─── Stage 1: Build ───────────────────────────────────────────────────────────
# Use Debian-based (glibc) image — NOT alpine.
# pnpm-workspace.yaml excludes musl (*-linux-x64-musl) native binaries for
# tailwindcss-oxide, lightningcss, and rollup. Alpine uses musl, so those
# binaries would be missing and the frontend build would crash.
FROM node:24 AS builder
WORKDIR /app

# Match the pnpm version used in development (v10.x).
# The lockfile was generated by pnpm 10; pnpm 9 cannot read it reliably
# and does not support workspace features like minimumReleaseAge.
RUN npm install -g pnpm@10

# Workspace manifest files
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./

# Both tsconfig files are required — tsconfig.base.json is extended by every
# package; without it the TypeScript composite build fails to resolve references.
COPY tsconfig.json tsconfig.base.json ./

# Source packages
COPY lib/ ./lib/
COPY scripts/ ./scripts/
COPY artifacts/api-server/ ./artifacts/api-server/
COPY artifacts/ryuu-vpn/ ./artifacts/ryuu-vpn/

# Install all dependencies
RUN pnpm install --frozen-lockfile

# Build frontend — BASE_PATH=/ so it runs at the domain root
RUN BASE_PATH=/ pnpm --filter @workspace/ryuu-vpn run build

# Build API server (esbuild bundles all deps into dist/)
RUN pnpm --filter @workspace/api-server run build

# ─── Stage 2: Production image ────────────────────────────────────────────────
# Alpine is fine here — the runner only executes the pre-bundled .mjs file,
# no native platform binaries are needed at runtime.
FROM node:24-alpine AS runner
WORKDIR /app

# Only copy the built artifacts — no node_modules needed (esbuild bundled everything)
COPY --from=builder /app/artifacts/api-server/dist ./artifacts/api-server/dist
COPY --from=builder /app/artifacts/ryuu-vpn/dist/public ./artifacts/ryuu-vpn/dist/public

ENV NODE_ENV=production
ENV PORT=8080

EXPOSE 8080

CMD ["node", "--enable-source-maps", "artifacts/api-server/dist/index.mjs"]
